# paths relative to project folder or absolute

folders:
  data_folder: './data'
  index_folder: './data/indices'
  lm_folder: '/Users/viktoriaknazkova/Desktop/me/study/github_repos/thesis_search/data/vector_models'

index_types:
  bm25: bm25
  w2v: word2vec
  ft: fasttext
  bert: bert

default_vector_models:
  w2v:
    file: 'ruwikiruscorpora_upos_cbow_300_10_2021.bin'
    source_link: 'http://vectors.nlpl.eu/repository/20/220.zip'
  ft:
    file: 'cc.ru.300.bin'
    source_link: 'https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ru.300.bin.gz'