folders:
  data_folder: ./data
  index_folder: ./data/indices
  lm_folder: /Users/viktoriaknazkova/Desktop/me/study/github_repos/thesis_search/data/vector_models
models_defaults:
  bert:
    name: bert
    model_name: sbert_large_nlu_ru
    model_path: ai-forever/sbert_large_nlu_ru
    similarity_metric: cosine
  bm25:
    name: bm25
    b: 0.75
    k: 2
  ft:
    name: fasttext
    filepath: cc.ru.300.bin
    source_link: https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ru.300.bin.gz
    similarity_metric: cosine
  w2v:
    name: w2v
    filepath: ruwikiruscorpora_upos_cbow_300_10_2021.bin
    source_link: http://vectors.nlpl.eu/repository/20/220.zip
    similarity_metric: cosine
