folders:
  data_folder: ./data
  index_folder: ./data/indices
  lm_folder: ./data/vector_models
models:
  bm25: bm25
  w2v: word2vec
  ft: fasttext
  bert: bert
defaults:
  freq:
    implementation: FreqMatrix
    preprocessor_: lemmatize
  bert:
    implementation: BertIndex
    preprocessor_: raw
    model_name: sbert_large_nlu_ru
    model_path: ai-forever/sbert_large_nlu_ru
    similarity_metric: cosine
  bm25:
    implementation: BM25Matrices
    preprocessor_: lemmatize
    b: 0.75
    k: 2
  ft:
    implementation: FastTextSearch
    preprocessor_: lemmatize
    model_name: cc.ru.300
    model_path: cc.ru.300.bin
    source_link: https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ru.300.bin.gz
    similarity_metric: cosine
  w2v:
    implementation: Word2VecSearch
    preprocessor_: lemmatize
    model_name: ruwikiruscorpora_upos_cbow_300_10_2021
    model_path: ruwikiruscorpora_upos_cbow_300_10_2021.bin
    source_link: http://vectors.nlpl.eu/repository/20/220.zip
    similarity_metric: cosine
