folders:
  data_folder: ./data
  index_folder: ./data/indices
  lm_folder: /Users/viktoriaknazkova/Desktop/me/study/github_repos/thesis_search/data/vector_models
index_types:
  bert: bert
  bm25: bm25
  ft: fasttext
  w2v: word2vec
models_defaults:
  bert:
    model_name: sbert_large_nlu_ru
    model_path: ai-forever/sbert_large_nlu_ru
    similarity_metric: cosine
  bm25:
    b: 0.75
    k: 2
  ft:
    file: cc.ru.300.bin
    similarity_metric: cosine
    source_link: https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ru.300.bin.gz
  w2v:
    file: ruwikiruscorpora_upos_cbow_300_10_2021.bin
    similarity_metric: cosine
    source_link: http://vectors.nlpl.eu/repository/20/220.zip
